### ISSUE TITLE
Should not redirect for POST

### ISSUE THREAD

**Issue by bdukes** [schourode/canonicalize#3]
We had an issue where the `<form/>`'s action URL wasn't being generated to match the criteria specified by Canonicalize, and the POST would never get to the application.  It seems like we don't want redirects on POSTs, only GETs.

**Comment by andpoulsen** [comment]
Yeah, I've been bugged by this issue too.

**Comment by schourode** [comment]
While _Canonicalize_ ensures that all incoming requests matches your applications URL scheme, the responsibility to output internal links in their canonical form is left with you. The [`AppendTrailingSlash`](http://msdn.microsoft.com/en-us/library/system.web.routing.routecollection.appendtrailingslash.aspx) and [`LowercaseUrls`](http://msdn.microsoft.com/en-us/library/system.web.routing.routecollection.lowercaseurls.aspx) options – introduced in .NET 4.5 – can be useful in this regard.

That said, I believe you are right about never wanting to redirect POST requests, as most browsers seem to switch to GET on 301. I have pushed Canonicalize 1.2 to NuGet today, with the proposed change – only GET and HEAD requests are now redirected according to canonicalization strategies,
