### ISSUE TITLE
Is it possible to generate URLs with a trailing slash?

### ISSUE THREAD

**Issue by bdukes** [schourode/canonicalize#4]
We were trying to use the `TrailingSlash` strategy, but could never get MVC to generate URLs with a trailing slash.  Are we missing something, or is this strategy impossible to implement?

**Comment by schourode** [comment]
While _Canonicalize_ ensures that all incoming requests matches your applications URL scheme, the responsibility to output internal links in their canonical form is left with you. The [`AppendTrailingSlash`](http://msdn.microsoft.com/en-us/library/system.web.routing.routecollection.appendtrailingslash.aspx) option – introduced in .NET 4.5 – can be useful in this regard.
