### ISSUE TITLE
Generate URLs based on Canonicalize criteria

### ISSUE THREAD

**Issue by bdukes** [schourode/canonicalize#5]
It looks like Canonicalize is only in the business of redirecting bad URLs, not generating good URLs.  It'd be great if it could help generate the right URL initially, so the application isn't having to redirect everywhere or use another library to generate the URLs.

**Comment by schourode** [comment]
While _Canonicalize_ ensures that all incoming requests matches your applications URL scheme, the responsibility to output internal links in their canonical form is left with you. The [`AppendTrailingSlash`](http://msdn.microsoft.com/en-us/library/system.web.routing.routecollection.appendtrailingslash.aspx) and [`LowercaseUrls`](http://msdn.microsoft.com/en-us/library/system.web.routing.routecollection.lowercaseurls.aspx) options – introduced in .NET 4.5 – can be useful in this regard.
