### ISSUE TITLE
GetRouteData() Method or operation is not implemented.

### ISSUE THREAD

**Issue by cristian-eriomenco** [schourode/canonicalize#7]
Hi! Although Canonicalize is a great plugin, Today I've been struggling an issue with it. When trying to iterate through RouteTables, and call GetRouteData method, the plugin has thrown an exception : 

```
[NotImplementedException: The method or operation is not implemented.]
System.Web.HttpRequestBase.get_HttpMethod() +29
Canonicalize.CanonicalizeRoute.GetRouteData(HttpContextBase httpContext) +72
```

The solution was quite simple. Before iterating through routetables i've ignored Canonicalize route, and then called GetRouteData. Here is a sample:

```
    public RouteData DoWork(Uri uri, string applicationPath)
    {
        var routes = new RouteCollection();
        foreach (var allowedRoute in RouteTable.Routes.Where(x => x.GetType().Name !=     typeof(CanonicalizeRoute).Name))
        {
            routes.Add(allowedRoute);
        }
        var routeData = routes.GetRouteData(new InternalHttpContext(uri, applicationPath));
        return routeData;
    }
```

Today i'm struggling another issue with Telerik Extensions (Q2013). Seems that telerik is trying to access the GetRouteData() method in a similar way. Unfortunately I do not have access of overriding telerik's implementation, or to tell him to ignore Canonicalize route. The relevant part of the stack-trace is here:

```
The method or operation is not implemented.
```

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NotImplementedException: The method or operation is not implemented.

Source Error: 

Line 67:     <div id="main-nagivation-menu">
Line 68: 
Line 69:         @{Html.Telerik().PanelBar()
Line 70:               .Name("AdminMenu")
Line 71:               .Items(panelbar =>

Source File: d:\Repositories\CyberSystems-Vendmax\Vendmax.UI\Views\Shared_AdminMenu.cshtml    Line: 69 

Stack Trace: 

[NotImplementedException: The method or operation is not implemented.]
   System.Web.HttpRequestBase.get_HttpMethod() +29
   Canonicalize.CanonicalizeRoute.GetRouteData(HttpContextBase httpContext) +72
   System.Web.Routing.RouteCollection.GetRouteData(HttpContextBase httpContext) +233
   Telerik.Web.Mvc.Infrastructure.Implementation.RouteDataCache.RouteDataFactory(String url) +82
   Telerik.Web.Mvc.Infrastructure.Implementation.<>c__DisplayClass1.<GetRouteData>b__0() +45
   Telerik.Web.Mvc.Infrastructure.Implementation.NoCache.Get(String key, Func`1 defaultValueFactory) +41
   Telerik.Web.Mvc.Infrastructure.Implementation.RouteDataCache.GetRouteData(String key, String url) +176
   Telerik.Web.Mvc.Infrastructure.Implementation.AuthorizationContextCache.GetAuthorizationContext(RequestContext request, String controllerName, String actionName, RouteValueDictionary routeValues) +617
   Telerik.Web.Mvc.Infrastructure.Implementation.ControllerAuthorization.IsAccessibleToUser(RequestContext requestContext, String controllerName, String actionName, RouteValueDictionary routeValues) +149
   Telerik.Web.Mvc.Infrastructure.Implementation.NavigationItemAuthorization.IsAccessibleToUser(RequestContext requestContext, INavigatable navigationItem) +308
   Telerik.Web.Mvc.UI.<>c__DisplayClass2`1.<IsAccessible>b__1(T item) +84
   System.Linq.Enumerable.Any(IEnumerable`1 source, Func`2 predicate) +146
   Telerik.Web.Mvc.UI.NavigatableExtensions.IsAccessible(IEnumerable`1 items, INavigationItemAuthorization authorization, ViewContext viewContext) +254
   Telerik.Web.Mvc.UI.NavigationItemContainerExtensions.WriteItem(TItem item, TComponent component, IHtmlNode parentTag, INavigationComponentHtmlBuilder`1 builder) +1293
   Telerik.Web.Mvc.UI.<>c__DisplayClass4.<WriteHtml>b__3(PanelBarItem item) +123
   Telerik.Web.Mvc.Extensions.EnumerableExtensions.Each(IEnumerable`1 instance, Action`1 action) +194
   Telerik.Web.Mvc.UI.PanelBar.WriteHtml(HtmlTextWriter writer) +456
   Telerik.Web.Mvc.UI.ViewComponentBase.Render() +125
   Telerik.Web.Mvc.UI.ViewComponentBuilderBase`2.Render() +58
   ASP._Page_Views_Shared__AdminMenu_cshtml.Execute() in d:\Repositories\CyberSystems-  Vendmax\Vendmax.UI\Views\Shared_AdminMenu.cshtml:69

How to deal with this situation? Thank you very much

**Comment by schourode** [comment]
It seems that your `InternalHttpContext` class exposes a specialization of `HttpRequestBase` which does not implement the [`HttpMethod` property](http://msdn.microsoft.com/en-us/library/vstudio/system.web.httprequestbase.httpmethod%28v=vs.100%29.aspx). Canonicalize tries to [access this property](https://github.com/schourode/canonicalize/blob/master/Canonicalize/CanonicalizeRoute.cs#L47), and the exception is thrown.

I do not think that Canonicalize is doing anything wrong here. If you implement the `HttpMethod` in your request abatraction the exception should go away,

**Comment by cristian-eriomenco** [comment]
Thank you for your response. I've analyzed the source code and You're right, the Property HttpMethod wasn't setted. Thank you again!
